### ISSUE TITLE
老铁，我上传到空间了

### ISSUE THREAD

**Issue by ghost** [qqwhwmt5/Fuck-zhuoyao_radar#1]
不知道可不可以，电脑太麻烦，我就弄了个网站。要是不可以的话我马上删除。征求您的意见。http://zhuoyao.3vdo.net/index.html

**Comment by 921600646** [comment]
老哥可否给个源码？

**Comment by qqwhwmt5** [comment]
> 不知道可不可以，电脑太麻烦，我就弄了个网站。要是不可以的话我马上删除。征求您的意见。http://zhuoyao.3vdo.net/index.html

可以

**Comment by ChoKhoOu** [comment]
> 不知道可不可以，电脑太麻烦，我就弄了个网站。要是不可以的话我马上删除。征求您的意见。http://zhuoyao.3vdo.net/index.html

大哥 我说你这网站的密码也太.... 2333333     前端校验...
